environment:
  global:
    VisualStudio: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC"'
    ZLib_repo: "https://github.com/madler/zlib"
  matrix:
  - configuration: release
  - configuration: debug
  

platform:
  - x86
  - amd64


init:
  - '%VisualStudio%\vcvarsall.bat %platform%'

install:
  # Get zlib source from GIT
  - git clone -q --branch=master %ZLib_repo% zlib
   
before_build:
   - cd zlib
   - if %configuration%==release echo nmake -f win32/Makefile.msc LOC="-DASMV -DASMINF" OBJA="inffas32.obj match686.obj" > x86.bat
   - if %configuration%==release echo nmake -f win32/Makefile.msc AS=ml64 LOC="-DASMV -DASMINF -I." OBJA="inffasx64.obj gvmat64.obj inffas8664.obj" > x64.bat
   - if %configuration%==debug echo nmake -f win32/Makefile.msc LOC="-DASMV -DASMINF -MDd" OBJA="inffas32.obj match686.obj" > x86.bat
   - if %configuration%==debug echo nmake -f win32/Makefile.msc AS=ml64 LOC="-DASMV -DASMINF -I. -MDd" OBJA="inffasx64.obj gvmat64.obj inffas8664.obj" > x64.bat
   - cd ..

build_script:                                                                                   
  # Build
   - cd zlib
   - if %platform%==x86 x86.bat
   - if %platform%==X64 x64.bat
   - cd ..
   
after_build:
   - mkdir d
   - mkdir d\include
   - mkdir d\lib
   - mkdir d\bin
   - copy zlib\zlib.h d\include
   - copy zlib\zconf.h d\include
   - copy zlib\zlib.lib d\lib
   - copy zlib\zlib.pdb d\lib
   - copy zlib\zdll.lib d\lib
   - copy zlib\zlib1.dll d\bin
   - copy zlib\zlib1.pdb d\bin
   - cd d
   - 7z a -r -y ..\zlib-%platform%-%configuration%.7z *.*
   
test: off

artifacts:
   - path: zlib-%platform%-%configuration%.7z
   
deploy:
- provider: GitHub
  release: $(appveyor_build_version)
  description: 'ZLib build [$(appveyor_build_version)]'
  auth_token:
    secure: 7fz/vsEpOOUyPYNmrykrY4lgqu3XQsag6g4x25nOwtd2dM2kc3X3GPoPzMCMDno/
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: false        # deploy on tag push only
