environment:
  global:
    VisualStudio: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC"'
    ZLib_repo: "https://github.com/madler/zlib"

platform:
  - x86
  - amd64


init:
  - '%VisualStudio%\vcvarsall.bat %platform%'

install:
  # Get zlib source from GIT
  - git clone -q --branch=master %ZLib_repo% zlib
   
build_script:                                                                                   
  # Build
   - cd zlib
   - if %platform%==x86 nmake -f win32/Makefile.msc LOC="-DASMV -DASMINF -Zi" OBJA="inffas32.obj match686.obj"
   - if %platform%==X64 nmake -f win32/Makefile.msc AS=ml64 LOC="-DASMV -DASMINF -I. -Zi" OBJA="inffasx64.obj gvmat64.obj inffas8664.obj
   - cd ..
   
after_build:
   - mkdir d
   - mkdir d\include
   - mkdir d\lib
   - mkdir d\bin
   - copy zlib\zlib.h d\include
   - copy zlib\zconf.h d\include
   - copy zlib\zlib.lib d\lib
   - copy zlib\zlib.pdb d\lib
   - copy zlib\zdll.lib d\lib
   - copy zlib\zlib1.dll d\bin
   - copy zlib\zlib1.pdb d\bin
   - cd d
   - 7z a -r -y ..\zlib.7z *.*
   
test: off

artifacts:
   - path: zlib.7z

