environment:
  global:
    VisualStudio: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC"'
    ZLib_repo: "https://github.com/madler/zlib"

platform:
  - x86
  - amd64

init:
  - '%VisualStudio%\vcvarsall.bat %platform%'

install:
  # Get zlib source from GIT
  - git clone -q --branch=master %ZLib_repo% zlib
   
build_script:                                                                                   
  # Build
   - echo %platform%
   - cd zlib
   - if %platform%==x86 nmake -f win32/Makefile.msc LOC="-DASMV -DASMINF" OBJA="inffas32.obj match686.obj"
  # amd64 magically becomes X64 at this point
   - if %platform%==X64 nmake -f win32/Makefile.msc AS=ml64 LOC="-DASMV -DASMINF -I." OBJA="inffasx64.obj gvmat64.obj inffas8664.obj
   - cd ..
   - mkdir include
   - mkdir lib
   - mkdir bin
   - copy zlib\zlib.h include
   - copy zlib\zlib.lib lib
   - copy zlib\zdll.lib lib
   - copy zlib\zlib1.dll bin
   
test: off

artifacts:
   - path: lib\zlib.lib
   - path: bin\zlib1.dll
   - path: lib\zdll.lib
   - path: include\zlib.h

